name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./suika
    steps:
    - uses: actions/checkout@v2
    - name: Install nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: clippy
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build --verbose
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: tests --verbose
    - name: Run clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy -- -D warnings
